name: LUFINHA Kite School
favicon: null
layout_spectrum: 0.8503578258678317
typography_spectrum: 0.10468185297213495
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5294892454985529
  lightness: 0.5528497355990112
  saturation: 0.8722541213501245
  rhythmicContrast: 0.8812174792401493
purpose: []
