name: LUFINHA Kite School
favicon: null
layout_spectrum: 0.8503578258678317
typography_spectrum: 0.10468185297213495
title: LUFINHA KITESURF SCHOOL
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefbe8'
    - '#b0dfe5'
    - '#626e64'
    - '#9a9077'
    - '#2b2613'
  brandStrength: 0.5625
  lightness: 0.5528497355990112
  saturation: 0.8722541213501245
  rhythmicContrast: 0.8812174792401493
purpose: []
